version: '3'

services:
  app:
    container_name: typescript-crud-example-app
    build: .
    command: npm run dev
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/TypescriptCrudExample
    ports:
      - '3333:3333'
    volumes:
      - .:/usr/app

  mongodb:
    container_name: typescript-crud-example-mongodb
    image: mongo
    ports:
      - '27017:27017'
